version: '3.8'

services:
  ondi-website-dev:
    image: node:20-alpine
    container_name: ondi-website-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - ondi-network-dev

networks:
  ondi-network-dev:
    driver: bridge
